steps:
- name: maven:3-jdk-8
  args: ['mvn', '--version']
#steps:
- name: maven:3-jdk-8
  args: ['mvn', 'test']
#steps:
- name: maven:3-jdk-8
  args: ['mvn', 'package', '-Dmaven.test.skip=true']
#- name: 'gcr.io/cloud-builders/gcloud'
 # args: ['auth', 'configure-maven', 'asia-south1-maven.pkg.dev', '--quiet' ]
#- name: gcr.io/cloud-builders/mvn
 # args: ['deploy:deploy-file', '-Durl=artifactregistry://asia-south1-maven.pkg.dev/business-transformers/suchita-mavan-repo', '-Dfile=target/spring-petclinic-2.4.2.jar']
  
#steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/business-transformers/my-source-repo-suchita/spring-petclinic:$SHORT_SHA', '--build-arg=JAR_FILE=target/spring-petclinic-2.4.2.jar', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'configure-docker', 'asia-south1-docker.pkg.dev', '--quiet' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/business-transformers/my-source-repo-suchita/spring-petclinic:$SHORT_SHA']
  
#- name: maven:3-jdk-8 
 # args: ['mvn', 'deploy:deploy-file', '-Durl=artifactregistry://asia-south1-docker.pkg.dev/business-transformers/my-source-repo-suchita', '-Dfile=target/spring-petclinic-2.4.2.jar']
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=suchita-cluster-gke'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'my-source-repo-suchita', 
   'my-source-repo-suchita=asia-south1-docker.pkg.dev/business-transformers/my-source-repo-suchita/spring-petclinic:$SHORT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=suchita-cluster-gke'
images: 
- 'asia-south1-docker.pkg.dev/business-transformers/my-source-repo-suchita/spring-petclinic:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY

